### ISSUE TITLE
Maximum number of requests reached

### ISSUE THREAD

**Issue by Rutasd** [Rutasd/hearted_contributions#1]
Hi @gr2m 
This is the error I am facing
RequestError [HttpError]: API rate limit exceeded for user ID XXXXXXX.

**Comment by gr2m** [comment]
Was there more information in the error logs? I think it should log a JSON object with the full request and response (the token should be retracted).

Also please share how you run the command that results in the error

**Comment by Rutasd** [comment]
I think I might have fixed this since I am not getting this error now. But I'm not sure since I am getting a few other errors that I am working on. I will keep you updated

**Comment by gr2m** [comment]
I was able to reproduce it

```
RequestError [HttpError]: API rate limit exceeded for user ID 39992.
    at /Users/gr2m/code/rutasd/hearted_contributions/node_modules/@octokit/request/dist-node/index.js:122:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/Users/gr2m/code/rutasd/hearted_contributions/node_modules/@octokit/plugin-retry/dist-node/index.js:70:20)
    at async Job.doExecute (/Users/gr2m/code/rutasd/hearted_contributions/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/octokit/webhooks.js/pulls/587/reviews?per_page=100',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 07 Aug 2023 19:15:18 GMT',
      'github-authentication-token-expiration': '2023-11-02 23:16:35 UTC',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'E359:86B6:560F7B:58599D:64D142C6',
      'x-oauth-scopes': 'notifications, project, repo, workflow, write:org',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '0',
      'x-ratelimit-reset': '1691435718',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '5000',
      'x-xss-protection': '0'
    },
    data: {
      message: 'API rate limit exceeded for user ID 39992.',
      documentation_url: 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/octokit/webhooks.js/pulls/587/reviews?per_page=100',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/2.1.0 octokit-core.js/4.2.4 Node.js/20.4.0 (darwin; arm64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], retryCount: 0 }
  }
}
```

The relevant bits from GitHub's API response are these:

```
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '0',
      'x-ratelimit-reset': '1691435718',
```

This should not happen, Octokit should wait the correct amount of time as defined in `x-ratelimit-reset` before retrying, but something is not working as it should.

The reset time `1691435718` is `2023-08-07T19:15:18.000Z` (you can get it using this code: `new Date(1691435718000).toISOString()`)

The server time is `2023-08-07T19:15:18.000Z`, too, which I got by using the `date` response header value (`new Date('Mon, 07 Aug 2023 19:15:18 GMT').toISOString()`)

So there seems to be race condition, it's not your fault. I'll try to investigate what's happening. This didn't happen before.

For the time being, we can bump up the retries as documented here: https://github.com/octokit/plugin-throttling.js. By default, the `octokit` package retries once ([source code](https://github.com/octokit/octokit.js/blob/38c8cc7056347c65df5ecaf665bbdd579cb69e12/src/octokit.ts#L31-L54))

Set the `throttle` option here: https://github.com/Rutasd/hearted_contributions/blob/b8e85abeb2e45f9e0d80bea648309a374317fec1/index.js#L19-L21 Instead of `options.request.retryCount === 0` you can do something like `options.request.retryCount < 10` to check for 10 times
